spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_new
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  default-produces-media-type: application/json
